/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Dimension;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JToggleButton;
import model.Deposit;
import model.Node;
import model.Worker;

/**
 *
 * @author unalman
 */
public class MineFrame extends javax.swing.JFrame {

    private List<JToggleButton> buttons;
    private JFrame frame;

    //cuando se agregue el tamaño del mapa
    public MineFrame(int rows, int columns) {
        initComponents();
        loadMap(rows, columns);
        buttons = new LinkedList<>();
        //loadButtons();
    }

    //con tamaño fijo
    public MineFrame() {
        initComponents();
        buttons = new LinkedList<>();
        setBounds(200, 50, 600, 600);
        loadMap(20, 20);
        //loadButtons();
    }

    /**
     * @return the buttons
     */
    public List<JToggleButton> getButtons() {
        return buttons;
    }

    /**
     * @param buttons the buttons to set
     */
    public void setButtons(List<JToggleButton> buttons) {
        this.buttons = buttons;
    }

    /**
     * @return the frame
     */
    public JFrame getFrame() {
        return frame;
    }

    private void animate() {
        Node currentDeposit = panelMineCreator.getMine().obtainClosestDeposit();
        LinkedList<LinkedList<Node>> caminos = new LinkedList<LinkedList<Node>>();
        LinkedList<Node> listota = new LinkedList<Node>();
        while (currentDeposit != null) {
            LinkedList<Node> list = panelMineCreator.getMine().findPath(currentDeposit);
            list.add(panelMineCreator.getMine().getExit());
            listota.addAll(reverseList(list));
            System.out.println(panelMineCreator.getMine().QuantityDeposit(currentDeposit));
            listota.addAll(list);
            caminos.add(listota);
            currentDeposit = panelMineCreator.getMine().obtainClosestDeposit();
        }

        lookingForRoutes(caminos);

    }

    public void lookingForRoutes(LinkedList<LinkedList<Node>> caminos) {
        int sizeWorkers = panelMineCreator.getMine().getWorkers().size();
        LinkedList<Worker> listamineros = panelMineCreator.getMine().getWorkers();
        int sizeDeposits = panelMineCreator.getMine().getDeposits().size();
        if (!caminos.isEmpty()) {
            int i = 0;
            if (sizeWorkers == sizeDeposits) {
                for (Worker minero : listamineros) {
                    minero.setCurrentPath(caminos.get(i));
                    caminos.poll();
                }
            }
            if (sizeWorkers < sizeDeposits) {
                int j = 0;
                while (!caminos.isEmpty()) {
                    if (j == sizeWorkers) {
                        j = 0;
                    }
                    panelMineCreator.getMine().getWorkers().get(j).getPossiblePaths().add(caminos.get(i));
                    j++;
                    caminos.poll();
                }
            }
            if (sizeWorkers > sizeDeposits) {
                int k = 0;
                for (Worker minerito : listamineros) {
                    if (k == sizeDeposits) {
                        k = 0;
                    }
                    minerito.getPossiblePaths().add(caminos.get(k));
                    k++;
                }
            }
            this.panelMineCreator.getMine().start();
        }
    }

    private LinkedList<Node> reverseList(LinkedList<Node> l) {
        LinkedList<Node> reverse = new LinkedList<>();
        for (int i = (l.size() - 1); i >= 0; i--) {
            reverse.add(l.get(i));
        }
        return reverse;
    }

    /**
     * @param frame the frame to set
     */
    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMineCreator = new view.PanelMineCreator();
        btnCreateMine = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 700));
        setPreferredSize(new java.awt.Dimension(550, 700));

        panelMineCreator.setAlignmentX(0.5F);
        panelMineCreator.setAlignmentY(0.5F);
        panelMineCreator.setMaximumSize(new java.awt.Dimension(32700, 32700));
        panelMineCreator.setName(""); // NOI18N
        panelMineCreator.setPreferredSize(new java.awt.Dimension(500, 500));

        btnCreateMine.setText("Crear Mina");
        btnCreateMine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMineActionPerformed(evt);
            }
        });

        Iniciar.setText("Iniciar");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(panelMineCreator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnCreateMine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Iniciar)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(panelMineCreator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateMine)
                    .addComponent(Iniciar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateMineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMineActionPerformed
        setFrame(new MainFrame());
        getFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateMineActionPerformed

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        this.animate();
    }//GEN-LAST:event_IniciarActionPerformed

    private void loadMap(int rows, int columns) {
        getPanelMineCreator().setLocation(100, 50);
        getPanelMineCreator().setPreferredSize(new Dimension(550, 700));
        getPanelMineCreator().setBackground(Color.GRAY);
        //establecer tamaño por defecto de la cuadricula aqui
        getPanelMineCreator().setRowsCol(20, 20);
    }

//    private void loadButtons() {
//        getButtons().add(jToggleButtonExit);
//        getButtons().add(jToggleButtonDeposits);
//        getButtons().add(jToggleButtonPaths);
//    }
    private void deSelectButtons(JToggleButton btn) {
        for (JToggleButton littlebutton : getButtons()) {
            if (!littlebutton.equals(btn)) {
                littlebutton.setSelected(false);
            }
        }
    }

    private boolean isSomeoneSelected() {
        for (JToggleButton boton : getButtons()) {
            if (boton.isSelected()) {
                return true;
            }
        }
        return false;
    }

    private void ToogleButtonAction(int option, JToggleButton btn) {
        deSelectButtons(btn);
        getPanelMineCreator().setPaintable(isSomeoneSelected());
        getPanelMineCreator().setOptionselected(option);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton btnCreateMine;
    private view.PanelMineCreator panelMineCreator;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the panelMineCreator
     */
    public PanelMineCreator getPanelMineCreator() {
        return panelMineCreator;
    }

    /**
     * @param panelMineCreator the panelMineCreator to set
     */
    public void setPanelMineCreator(PanelMineCreator panelMineCreator) {
        this.panelMineCreator = panelMineCreator;
    }

}
