/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Class.Mine;
import java.awt.Dimension;
import java.util.Hashtable;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JToggleButton;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author unalman
 */
public class MineFrame extends javax.swing.JFrame {

    private Mine mine;
    private PanelMineCreator internalPanel;
    private List<JToggleButton> buttons;

    //cuando se agregue el tamaño del mapa
    public MineFrame(int rows, int columns) {
        initComponents();
        loadMap(rows, columns);
        buttons = new LinkedList<>();
        loadButtons();
    }

    //con tamaño fijo
    public MineFrame() {
        initComponents();
        buttons=new LinkedList<>();
        setBounds(200, 50, 600, 600);
        loadMap(10, 10);
        loadButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMineCreator1 = new view.PanelMineCreator();
        jToggleButtonDeposits = new javax.swing.JToggleButton();
        jToggleButtonPaths = new javax.swing.JToggleButton();
        jToggleButtonExit = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMineCreator1.setAlignmentX(0.5F);
        panelMineCreator1.setAlignmentY(0.5F);
        panelMineCreator1.setMaximumSize(new java.awt.Dimension(32700, 32700));
        panelMineCreator1.setName(""); // NOI18N
        panelMineCreator1.setPreferredSize(new java.awt.Dimension(500, 500));

        jToggleButtonDeposits.setText("2. Agrega Depósitos");
        jToggleButtonDeposits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDepositsActionPerformed(evt);
            }
        });

        jToggleButtonPaths.setText("3. Agrega Caminos");
        jToggleButtonPaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonPathsActionPerformed(evt);
            }
        });

        jToggleButtonExit.setText("1. Agrega Salida");
        jToggleButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panelMineCreator1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButtonExit)
                        .addContainerGap())
                    .addComponent(jToggleButtonDeposits, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButtonPaths)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMineCreator1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToggleButtonExit)
                        .addGap(18, 18, 18)
                        .addComponent(jToggleButtonDeposits)))
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonPaths)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonDepositsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDepositsActionPerformed
        ToogleButtonAction(2, jToggleButtonDeposits);
    }//GEN-LAST:event_jToggleButtonDepositsActionPerformed

    private void jToggleButtonPathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonPathsActionPerformed
         ToogleButtonAction(3, jToggleButtonPaths);
    }//GEN-LAST:event_jToggleButtonPathsActionPerformed

    private void jToggleButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExitActionPerformed
         ToogleButtonAction(1, jToggleButtonExit);
    }//GEN-LAST:event_jToggleButtonExitActionPerformed

    private void loadMap(int rows, int columns) {
        panelMineCreator1.setLocation(100, 50);
        //panelMineCreator1.setPreferredSize(new Dimension(500, 500));
        //establecer tamaño por defecto de la cuadricula aqui
        panelMineCreator1.setRowsCol(10, 10);
    }

    private void loadButtons() {
        buttons.add(jToggleButtonExit);
        buttons.add(jToggleButtonDeposits);
        buttons.add(jToggleButtonPaths);
    }

    private void deSelectButtons(JToggleButton btn) {
        for (JToggleButton littlebutton : buttons) {
            if (!littlebutton.equals(btn)) {
                littlebutton.setSelected(false);
            }
        }
    }

    private boolean isSomeoneSelected() {
        for (JToggleButton boton : buttons) {
            if (boton.isSelected()) {
                return true;
            }
        }
        return false;
    }

    private void ToogleButtonAction(int option, JToggleButton btn) {
        deSelectButtons(btn);
        panelMineCreator1.setPaint(isSomeoneSelected());
        panelMineCreator1.setOptionselected(option);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MineFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MineFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButtonDeposits;
    private javax.swing.JToggleButton jToggleButtonExit;
    private javax.swing.JToggleButton jToggleButtonPaths;
    private view.PanelMineCreator panelMineCreator1;
    // End of variables declaration//GEN-END:variables
}
